#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX 100

int tempVarCount = 1;

int isValidIdentifier(char *s)
{
    if (!isalpha(s[0]))
            return 0;
                for (int i = 1; s[i]; i++)
                    {
                            if (!isalnum(s[i]))
                                        return 0;
                                            }
                                                return 1;
                                                }

                                                void getTemp(char *temp)
                                                {
                                                    sprintf(temp, "t%d", tempVarCount++);
                                                    }

                                                    int precedence(char op)
                                                    {
                                                        if (op == '*' || op == '/')
                                                                return 2;
                                                                    if (op == '+' || op == '-')
                                                                            return 1;
                                                                                return 0;
                                                                                }

                                                                                int isOperator(char c)
                                                                                {
                                                                                    return c == '+' || c == '-' || c == '*' || c == '/';
                                                                                    }

                                                                                    typedef struct
                                                                                    {
                                                                                        char data[MAX];
                                                                                            int top;
                                                                                            } CharStack;

                                                                                            void initCharStack(CharStack *s)
                                                                                            {
                                                                                                s->top = -1;
                                                                                                }
                                                                                                void pushChar(CharStack *s, char c)
                                                                                                {
                                                                                                    s->data[++(s->top)] = c;
                                                                                                    }
                                                                                                    char popChar(CharStack *s)
                                                                                                    {
                                                                                                        return s->data[(s->top)--];
                                                                                                        }
                                                                                                        char peekChar(CharStack *s)
                                                                                                        {
                                                                                                            return s->data[s->top];
                                                                                                            }
                                                                                                            int isEmptyChar(CharStack *s)
                                                                                                            {
                                                                                                                return s->top == -1;
                                                                                                                }

                                                                                                                typedef struct
                                                                                                                {
                                                                                                                    char data[MAX][MAX];
                                                                                                                        int top;
                                                                                                                        } StringStack;

                                                                                                                        void initStringStack(StringStack *s)
                                                                                                                        {
                                                                                                                            s->top = -1;
                                                                                                                            }
                                                                                                                            void pushStr(StringStack *s, char *str)
                                                                                                                            {
                                                                                                                                strcpy(s->data[++(s->top)], str);
                                                                                                                                }
                                                                                                                                char* popStr(StringStack *s)
                                                                                                                                {
                                                                                                                                    return s->data[(s->top)--];
                                                                                                                                    }
                                                                                                                                    char* peekStr(StringStack *s)
                                                                                                                                    {
                                                                                                                                        return s->data[s->top];
                                                                                                                                        }

                                                                                                                                        int infixToPostfix(char tokens[][MAX], int n, char postfix[][MAX])
                                                                                                                                        {
                                                                                                                                            CharStack opStack;
                                                                                                                                                initCharStack(&opStack);
                                                                                                                                                    int j = 0;

                                                                                                                                                        for (int i = 0; i < n; i++)
                                                                                                                                                            {
                                                                                                                                                                    char *tok = tokens[i];

                                                                                                                                                                            if (isalpha(tok[0]) || isdigit(tok[0]))
                                                                                                                                                                                    {
                                                                                                                                                                                                strcpy(postfix[j++], tok);
                                                                                                                                                                                                        }
                                                                                                                                                                                                                else if (tok[0] == '(')
                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                    pushChar(&opStack, tok[0]);
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                    else if (tok[0] == ')')
                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                        while (!isEmptyChar(&opStack) && peekChar(&opStack) != '(')
                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                    char op[2] = {popChar(&opStack), '\0'};
                                                                                                                                                                                                                                                                                                                    strcpy(postfix[j++], op);
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            if (!isEmptyChar(&opStack) && peekChar(&opStack) == '(')
                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                        popChar(&opStack);
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                    else if (isOperator(tok[0]))
                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                        while (!isEmptyChar(&opStack) &&
                                                                                                                                                                                                                                                                                                                                                                                                                                            precedence(peekChar(&opStack)) >= precedence(tok[0]))
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        char op[2] = {popChar(&opStack), '\0'};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        strcpy(postfix[j++], op);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pushChar(&opStack, tok[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while (!isEmptyChar(&opStack))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            char op[2] = {popChar(&opStack), '\0'};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    strcpy(postfix[j++], op);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return j;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            void generateTAC(char postfix[][MAX], int n, char *lhs)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                StringStack s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    initStringStack(&s);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        char temp[MAX], op1[MAX], op2[MAX];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < n; i++)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isOperator(postfix[i][0]) && strlen(postfix[i]) == 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            strcpy(op2, popStr(&s));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        strcpy(op1, popStr(&s));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    getTemp(temp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("%s = %s %c %s\n", temp, op1, postfix[i][0], op2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pushStr(&s, temp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pushStr(&s, postfix[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("%s = %s\n", lhs, popStr(&s));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    char input[MAX];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        char tokens[50][MAX], postfix[50][MAX];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            char rhsTokens[50][MAX];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int tokenCount = 0, rhsCount = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    char lhs[MAX];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Enter expression (e.g., result = a * ( b + c ) ):\n> ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fgets(input, MAX, stdin);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input[strcspn(input, "\n")] = '\0';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    char *token = strtok(input, " \t");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while (token != NULL)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    strcpy(tokens[tokenCount++], token);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            token = strtok(NULL, " \t");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (tokenCount < 5 || strcmp(tokens[1], "=") != 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Error: Invalid format. Use format like: a = b + c\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                strcpy(lhs, tokens[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!isValidIdentifier(lhs))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Error: Invalid identifier on LHS.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 2; i < tokenCount; i++)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            strcpy(rhsTokens[rhsCount++], tokens[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("\nThree Address Code:\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int postfixCount = infixToPostfix(rhsTokens, rhsCount, postfix);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            generateTAC(postfix, postfixCount, lhs);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                